### PR TITLE
Apparently opengraph requires a title to work

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by edsu** [comment]
I think maybe the opengraph namespace needs to be declared?

http://ogp.spypixel.com/Pogo/checker/index.php?url=https%3A%2F%2Fwikipulse.herokuapp.com%2F

**Comment by waldyrious** [comment]
Yeah, looks like I need to do some reading, sorry. I'm not sure the image can be a local path either. I'll send a new patch as soon as I am more confident I got the parameters right.

**Comment by edsu** [comment]
It's no trouble at all :-)

**Comment by waldyrious** [comment]
Thanks for the patience :) Hopefully the new patch will work.

**Pull request merged**
